/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ahalh7876
 */
public class magicalmathmethods extends javax.swing.JFrame {

    /**
     * Creates new form magicalmathmethods
     */
    public magicalmathmethods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPnl = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        bigNmbrLbl = new javax.swing.JLabel();
        bigNmbrTf1 = new javax.swing.JTextField();
        bigNmbrTf2 = new javax.swing.JTextField();
        bigNmbrBtn = new javax.swing.JButton();
        bigNmbrOutputLbl = new javax.swing.JLabel();
        smallNmbrLbl1 = new javax.swing.JLabel();
        smallNmbrTf1 = new javax.swing.JTextField();
        smallNmbrTf2 = new javax.swing.JTextField();
        smallNmbrBtn = new javax.swing.JButton();
        smallNmbrOutputLbl1 = new javax.swing.JLabel();
        pwrNmbrOutputLbl2 = new javax.swing.JLabel();
        pwrNmbrBtn = new javax.swing.JButton();
        pwrNmbrTf1 = new javax.swing.JTextField();
        pwrNmbrTf2 = new javax.swing.JTextField();
        pwrNmbrLbl = new javax.swing.JLabel();
        pwrNmbrOutputLbl = new javax.swing.JLabel();
        bigNmbrBtn3 = new javax.swing.JButton();
        bigNmbrTf7 = new javax.swing.JTextField();
        bigNmbrTf8 = new javax.swing.JTextField();
        bigNmbrLbl3 = new javax.swing.JLabel();
        bigNmbrLbl4 = new javax.swing.JLabel();
        bigNmbrTf10 = new javax.swing.JTextField();
        bigNmbrBtn4 = new javax.swing.JButton();
        bigNmbrOutputLbl4 = new javax.swing.JLabel();
        bigNmbrOutputLbl5 = new javax.swing.JLabel();
        bigNmbrBtn5 = new javax.swing.JButton();
        bigNmbrLbl5 = new javax.swing.JLabel();
        bigNmbrTf12 = new javax.swing.JTextField();
        bigNmbrOutputLbl6 = new javax.swing.JLabel();
        bigNmbrBtn6 = new javax.swing.JButton();
        bigNmbrLbl6 = new javax.swing.JLabel();
        bigNmbrTf14 = new javax.swing.JTextField();
        bigNmbrOutputLbl7 = new javax.swing.JLabel();
        bigNmbrBtn7 = new javax.swing.JButton();
        bigNmbrTf16 = new javax.swing.JTextField();
        bigNmbrLbl7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgPnl.setBackground(new java.awt.Color(236, 221, 217));

        titleLbl.setFont(new java.awt.Font("StencilDEE", 0, 30)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 51, 51));
        titleLbl.setText("The Math Boi");

        bigNmbrLbl.setFont(new java.awt.Font("StencilDEE", 0, 14)); // NOI18N
        bigNmbrLbl.setText("Enter two numbers, then press the button to find the larger number");

        bigNmbrTf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigNmbrTf1ActionPerformed(evt);
            }
        });

        bigNmbrTf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigNmbrTf2ActionPerformed(evt);
            }
        });

        bigNmbrBtn.setText("Find Larger #");

        bigNmbrOutputLbl.setFont(new java.awt.Font("StencilDEE", 0, 14)); // NOI18N
        bigNmbrOutputLbl.setText("Larger #: ");

        smallNmbrLbl1.setFont(new java.awt.Font("StencilDEE", 0, 14)); // NOI18N
        smallNmbrLbl1.setText("Enter two numbers, then press the button to find the smaller number");

        smallNmbrTf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallNmbrTf1ActionPerformed(evt);
            }
        });

        smallNmbrTf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallNmbrTf2ActionPerformed(evt);
            }
        });

        smallNmbrBtn.setText("Find Smaller #");

        smallNmbrOutputLbl1.setFont(new java.awt.Font("StencilDEE", 0, 14)); // NOI18N
        smallNmbrOutputLbl1.setText("Smaller #: ");

        pwrNmbrOutputLbl2.setFont(new java.awt.Font("StencilDEE", 0, 14)); // NOI18N
        pwrNmbrOutputLbl2.setText("Power #: ");

        pwrNmbrBtn.setText("Find Power #");
        pwrNmbrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwrNmbrBtnActionPerformed(evt);
            }
        });

        pwrNmbrTf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwrNmbrTf1ActionPerformed(evt);
            }
        });

        pwrNmbrTf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwrNmbrTf2ActionPerformed(evt);
            }
        });

        pwrNmbrLbl.setFont(new java.awt.Font("StencilDEE", 0, 14)); // NOI18N
        pwrNmbrLbl.setText("Enter two numbers, then press the button to find the 1st # to the 2nd #");

        pwrNmbrOutputLbl.setFont(new java.awt.Font("StencilDEE", 0, 14)); // NOI18N
        pwrNmbrOutputLbl.setText("hypotenuse #: ");

        bigNmbrBtn3.setText("Find Hypotenuse #");
        bigNmbrBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigNmbrBtn3ActionPerformed(evt);
            }
        });

        bigNmbrTf7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigNmbrTf7ActionPerformed(evt);
            }
        });

        bigNmbrTf8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigNmbrTf8ActionPerformed(evt);
            }
        });

        bigNmbrLbl3.setFont(new java.awt.Font("StencilDEE", 0, 14)); // NOI18N
        bigNmbrLbl3.setText("Enter two numbers, then press the button to find the hypotenuse");

        bigNmbrLbl4.setFont(new java.awt.Font("StencilDEE", 0, 14)); // NOI18N
        bigNmbrLbl4.setText("Enter a number, then press button to round # down to nearest int");

        bigNmbrTf10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigNmbrTf10ActionPerformed(evt);
            }
        });

        bigNmbrBtn4.setText("Round # Down");
        bigNmbrBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigNmbrBtn4ActionPerformed(evt);
            }
        });

        bigNmbrOutputLbl4.setFont(new java.awt.Font("StencilDEE", 0, 14)); // NOI18N
        bigNmbrOutputLbl4.setText("rounded #: ");

        bigNmbrOutputLbl5.setFont(new java.awt.Font("StencilDEE", 0, 14)); // NOI18N
        bigNmbrOutputLbl5.setText("Rounded #:");

        bigNmbrBtn5.setText("Round # Up");

        bigNmbrLbl5.setFont(new java.awt.Font("StencilDEE", 0, 14)); // NOI18N
        bigNmbrLbl5.setText("Enter a number, then press button to round # up to nearest int");

        bigNmbrTf12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigNmbrTf12ActionPerformed(evt);
            }
        });

        bigNmbrOutputLbl6.setFont(new java.awt.Font("StencilDEE", 0, 14)); // NOI18N
        bigNmbrOutputLbl6.setText("Root #: ");

        bigNmbrBtn6.setText("Square Root #");

        bigNmbrLbl6.setFont(new java.awt.Font("StencilDEE", 0, 14)); // NOI18N
        bigNmbrLbl6.setText("Enter a Number, then press button to find the square root");

        bigNmbrTf14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigNmbrTf14ActionPerformed(evt);
            }
        });

        bigNmbrOutputLbl7.setFont(new java.awt.Font("StencilDEE", 0, 14)); // NOI18N
        bigNmbrOutputLbl7.setText("Radian #: ");

        bigNmbrBtn7.setText("Find Radian #");

        bigNmbrTf16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigNmbrTf16ActionPerformed(evt);
            }
        });

        bigNmbrLbl7.setFont(new java.awt.Font("StencilDEE", 0, 14)); // NOI18N
        bigNmbrLbl7.setText("Enter an angle in degrees, then press button to convert it to radians");

        javax.swing.GroupLayout bgPnlLayout = new javax.swing.GroupLayout(bgPnl);
        bgPnl.setLayout(bgPnlLayout);
        bgPnlLayout.setHorizontalGroup(
            bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPnlLayout.createSequentialGroup()
                        .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPnlLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pwrNmbrLbl)
                                    .addGroup(bgPnlLayout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(pwrNmbrTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(pwrNmbrTf2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(pwrNmbrBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(pwrNmbrOutputLbl2))))
                            .addGroup(bgPnlLayout.createSequentialGroup()
                                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bigNmbrLbl)
                                    .addGroup(bgPnlLayout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(bigNmbrTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bigNmbrTf2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bigNmbrBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(bigNmbrOutputLbl))
                                    .addComponent(bigNmbrLbl3)
                                    .addGroup(bgPnlLayout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(bigNmbrTf7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bigNmbrTf8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bigNmbrBtn3)
                                        .addGap(18, 18, 18)
                                        .addComponent(pwrNmbrOutputLbl))
                                    .addComponent(bigNmbrLbl5)
                                    .addGroup(bgPnlLayout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(bigNmbrTf12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(136, 136, 136)
                                        .addComponent(bigNmbrBtn5)
                                        .addGap(18, 18, 18)
                                        .addComponent(bigNmbrOutputLbl5)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgPnlLayout.createSequentialGroup()
                                .addComponent(smallNmbrTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(smallNmbrTf2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(smallNmbrBtn)
                                .addGap(18, 18, 18)
                                .addComponent(smallNmbrOutputLbl1))
                            .addGroup(bgPnlLayout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(titleLbl)
                                .addGap(155, 155, 155))))
                    .addGroup(bgPnlLayout.createSequentialGroup()
                        .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bigNmbrLbl4)
                            .addComponent(smallNmbrLbl1)
                            .addComponent(bigNmbrLbl7)
                            .addComponent(bigNmbrLbl6)
                            .addGroup(bgPnlLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgPnlLayout.createSequentialGroup()
                                        .addComponent(bigNmbrTf10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(136, 136, 136)
                                        .addComponent(bigNmbrBtn4)
                                        .addGap(18, 18, 18)
                                        .addComponent(bigNmbrOutputLbl4))
                                    .addGroup(bgPnlLayout.createSequentialGroup()
                                        .addComponent(bigNmbrTf16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(136, 136, 136)
                                        .addComponent(bigNmbrBtn7)
                                        .addGap(18, 18, 18)
                                        .addComponent(bigNmbrOutputLbl7))
                                    .addGroup(bgPnlLayout.createSequentialGroup()
                                        .addComponent(bigNmbrTf14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(136, 136, 136)
                                        .addComponent(bigNmbrBtn6)
                                        .addGap(18, 18, 18)
                                        .addComponent(bigNmbrOutputLbl6)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        bgPnlLayout.setVerticalGroup(
            bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addComponent(bigNmbrLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bigNmbrTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bigNmbrTf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bigNmbrBtn)
                    .addComponent(bigNmbrOutputLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(smallNmbrLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smallNmbrTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smallNmbrTf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smallNmbrBtn)
                    .addComponent(smallNmbrOutputLbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pwrNmbrLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwrNmbrTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwrNmbrTf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwrNmbrBtn)
                    .addComponent(pwrNmbrOutputLbl2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bigNmbrLbl3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bigNmbrTf7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bigNmbrTf8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bigNmbrBtn3)
                    .addComponent(pwrNmbrOutputLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bigNmbrLbl4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bigNmbrTf10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bigNmbrBtn4)
                    .addComponent(bigNmbrOutputLbl4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bigNmbrLbl5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bigNmbrTf12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bigNmbrBtn5)
                    .addComponent(bigNmbrOutputLbl5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bigNmbrLbl6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bigNmbrTf14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bigNmbrBtn6)
                    .addComponent(bigNmbrOutputLbl6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bigNmbrLbl7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bigNmbrTf16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bigNmbrBtn7)
                    .addComponent(bigNmbrOutputLbl7))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bigNmbrTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigNmbrTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bigNmbrTf1ActionPerformed

    private void bigNmbrTf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigNmbrTf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bigNmbrTf2ActionPerformed

    private void smallNmbrTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallNmbrTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallNmbrTf1ActionPerformed

    private void smallNmbrTf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallNmbrTf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallNmbrTf2ActionPerformed

    private void pwrNmbrTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwrNmbrTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwrNmbrTf1ActionPerformed

    private void pwrNmbrTf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwrNmbrTf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwrNmbrTf2ActionPerformed

    private void bigNmbrTf7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigNmbrTf7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bigNmbrTf7ActionPerformed

    private void bigNmbrTf8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigNmbrTf8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bigNmbrTf8ActionPerformed

    private void bigNmbrTf10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigNmbrTf10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bigNmbrTf10ActionPerformed

    private void bigNmbrTf12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigNmbrTf12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bigNmbrTf12ActionPerformed

    private void bigNmbrTf14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigNmbrTf14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bigNmbrTf14ActionPerformed

    private void bigNmbrTf16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigNmbrTf16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bigNmbrTf16ActionPerformed

    private void pwrNmbrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwrNmbrBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwrNmbrBtnActionPerformed

    private void bigNmbrBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigNmbrBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bigNmbrBtn3ActionPerformed

    private void bigNmbrBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigNmbrBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bigNmbrBtn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(magicalmathmethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(magicalmathmethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(magicalmathmethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(magicalmathmethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new magicalmathmethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPnl;
    private javax.swing.JButton bigNmbrBtn;
    private javax.swing.JButton bigNmbrBtn3;
    private javax.swing.JButton bigNmbrBtn4;
    private javax.swing.JButton bigNmbrBtn5;
    private javax.swing.JButton bigNmbrBtn6;
    private javax.swing.JButton bigNmbrBtn7;
    private javax.swing.JLabel bigNmbrLbl;
    private javax.swing.JLabel bigNmbrLbl3;
    private javax.swing.JLabel bigNmbrLbl4;
    private javax.swing.JLabel bigNmbrLbl5;
    private javax.swing.JLabel bigNmbrLbl6;
    private javax.swing.JLabel bigNmbrLbl7;
    private javax.swing.JLabel bigNmbrOutputLbl;
    private javax.swing.JLabel bigNmbrOutputLbl4;
    private javax.swing.JLabel bigNmbrOutputLbl5;
    private javax.swing.JLabel bigNmbrOutputLbl6;
    private javax.swing.JLabel bigNmbrOutputLbl7;
    private javax.swing.JTextField bigNmbrTf1;
    private javax.swing.JTextField bigNmbrTf10;
    private javax.swing.JTextField bigNmbrTf12;
    private javax.swing.JTextField bigNmbrTf14;
    private javax.swing.JTextField bigNmbrTf16;
    private javax.swing.JTextField bigNmbrTf2;
    private javax.swing.JTextField bigNmbrTf7;
    private javax.swing.JTextField bigNmbrTf8;
    private javax.swing.JButton pwrNmbrBtn;
    private javax.swing.JLabel pwrNmbrLbl;
    private javax.swing.JLabel pwrNmbrOutputLbl;
    private javax.swing.JLabel pwrNmbrOutputLbl2;
    private javax.swing.JTextField pwrNmbrTf1;
    private javax.swing.JTextField pwrNmbrTf2;
    private javax.swing.JButton smallNmbrBtn;
    private javax.swing.JLabel smallNmbrLbl1;
    private javax.swing.JLabel smallNmbrOutputLbl1;
    private javax.swing.JTextField smallNmbrTf1;
    private javax.swing.JTextField smallNmbrTf2;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
